name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5.0.7
      with:
        file: coverage.out
        flags: unittests
        name: codecov-umbrella
        slug: jasonbirchall/lazycommit
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}