name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0

    - name: Run linter
      run: make lint