name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: make deps

    - name: Run tests
      run: make test